[workspace]
members = ["macro"]

[package]
name = "tondi-script"
version = "0.1.0"
edition = "2021"

[features]
serde = ["dep:serde", "tondi-consensus-core/serde"]

[dependencies]
tondi-consensus-core = { version = "0.17.0", path = "../Tondi/consensus/core" }
tondi-txscript = { version = "0.17.0", path = "../Tondi/crypto/txscript" }
script-macro = { path = "./macro" }
stdext = "0.3.3"
serde = { version = "1", features = ["derive"], optional = true }

[dev-dependencies]
bincode = "1.3.3"
